apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret-multidb
type: Opaque
data:
  # DATABASE_NAMES is no longer here; it's moved to db-configma
  # Logical database 1: 'prod'
  PROD_DB_HOST: <base64-encoded-prod-db-host>
  PROD_DB_PORT: <base64-encoded-prod-db-port>
  PROD_DB_USER: <base64-encoded-prod-db-user>
  PROD_DB_PASSWORD: <base64-encoded-prod-db-password>
  PROD_DB_DBNAME: <base64-encoded-prod-db-name
  # Logical database 2: 'analytics'
  ANALYTICS_DB_HOST: <base64-encoded-analytics-db-host>
  ANALYTICS_DB_PORT: <base64-encoded-analytics-db-port>
  ANALYTICS_DB_USER: <base64-encoded-analytics-db-user>
  ANALYTICS_DB_PASSWORD: <base64-encoded-analytics-db-password>
  ANALYTICS_DB_DBNAME: <base64-encoded-analytics-db-name
  # Add more database configurations here following the same PROD_DB_* pattern
    
