# servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-flask-app-multidb-monitor
  labels:
    prometheus: user-workload
spec:
  selector:
    matchLabels:
      app: my-flask-app-multidb # Selects the service with this label
  endpoints:
  - port: flask # The port defined in your Service (targetPort is 5000)
    path: /metrics # The endpoint where your Flask app exposes Prometheus metrics
    interval: 15s # How often Prometheus should scrape this endpoint
    scrapeTimeout: 10s # Timeout for scraping
