apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret
data: # For sensitive data, use 'data' and base64 encode values.
  # Example: echo -n 'myuser' | base64
  DB_USER: "bXl1c2Vy" # base64 encoded 'myuser'
  # Example: echo -n 'my_secure_password' | base64
  DB_PASSWORD: "bXlfc2VjdXJlX3Bhc3N3b3Jk" # base64 encoded 'my_secure_password'
  # Example: echo -n 'your-db-service.your-project.svc.cluster.local' | base64
  DB_HOST: "eW91ci1kYi1zZXJ2aWNlLnlvdXItcHJvamVjdC5zdmMuY2x1c3Rlci5sb2NhbA==" # base64 encoded DB host
  # Example: echo -n '5432' | base64
  DB_PORT: "NTQzMg==" # base64 encoded '5432'
type: Opaque