# deployment.yaml (Kubernetes Deployment instead of OpenShift DeploymentConfig)
apiVersion: apps/v1 # Changed from apps.openshift.io/v1
kind: Deployment # Changed from DeploymentConfig
metadata:
  name: flask-db-metrics-app
  labels:
    app: flask-db-metrics-app
spec:
  replicas: 1
  selector: # Added selector to match template labels
    matchLabels:
      app: flask-db-metrics-app
  template:
    metadata:
      labels:
        app: flask-db-metrics-app
    spec:
      containers:
      - name: flask-db-metrics-app
        image: ghcr.io/rosariovinoth/myk8sapp:latest
        ports:
        - containerPort: 5000 # The port your Flask app listens on
        env:
        # Inject DB_NAME and DB_WRITE_INTERVAL_SECONDS from app-config-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DB_NAME
        - name: DB_WRITE_INTERVAL_SECONDS
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DB_WRITE_INTERVAL_SECONDS

        # Inject database credentials from db-credentials-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials-secret
              key: DB_PORT
        # Set to "true" to see simulated failures/timeouts
        - name: SIMULATE_DB_FAILURE
          value: "false" 
